// <auto-generated />
namespace BTLLTQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class create_5_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_5_table));
        
        string IMigrationMetadata.Id
        {
            get { return "202111240842053_create_5_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
