// <auto-generated />
namespace BTLLTQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class crate_tabe_DangNhap : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(crate_tabe_DangNhap));
        
        string IMigrationMetadata.Id
        {
            get { return "202112100306543_crate_tabe_DangNhap"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
